/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import { MeasurementService, measurementService } from "./MeasurementService";
export type Services = {
    measurement: MeasurementService;
};
export const services = {
    measurement: measurementService
} as const;
